from __future__ import annotations

import base64
import json
from io import BytesIO
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

import pandas as pd


def _notebook_cell(cell_type: str, source: list[str]) -> dict[str, Any]:
    cell: dict[str, Any] = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source,
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell


def build_colab_notebook(
    df: pd.DataFrame,
    metadata: dict[str, Any],
) -> BytesIO:
    csv_payload = df.to_csv(index=False).encode("utf-8")
    encoded_csv = base64.b64encode(csv_payload).decode("ascii")
    metadata_json = json.dumps(metadata, indent=2)

    protected = metadata.get("protected_attribute") or ""
    outcome = metadata.get("outcome_column") or ""

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "colab": {"name": "bAIsed fairness audit export.ipynb"},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "cells": [
            _notebook_cell(
                "markdown",
                [
                    "# 📊 bAIsed Fairness Audit Export\n",
                    "\n",
                    "This notebook was auto-generated by the **bAIsed Fairness Workbench**.\n",
                    "It contains your standardized dataset, the protected attributes, and fairness metric calculation cells.\n",
                    "\n",
                    "**Instructions:**\n",
                    "1. Run the setup cell to load the dataset into pandas.\n",
                    "2. Run the metric calculation cell to see group-level selection rates, Disparate Impact Ratio (DIR), and Statistical Parity Difference (SPD).\n",
                    "3. Optionally, use the Gemini Prompt at the bottom to perform an AI-driven fairness audit.\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    "import base64\n",
                    "import io\n",
                    "import json\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "sns.set_theme(style=\"whitegrid\")\n",
                    f"metadata = json.loads({metadata_json!r})\n",
                    f"csv_bytes = base64.b64decode({encoded_csv!r})\n",
                    "df = pd.read_csv(io.BytesIO(csv_bytes))\n",
                    "df.head().style.set_properties(**{'background-color': '#f8f9fa', 'color': '#212529'})\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    f"protected_attribute = {protected!r} or metadata.get('protected_attribute')\n",
                    f"outcome_column = {outcome!r} or metadata.get('outcome_column')\n",
                    "print(f'\\033[1mProtected attribute:\\033[0m {protected_attribute}')\n",
                    "print(f'\\033[1mOutcome column:\\033[0m {outcome_column}')\n",
                    "print(f'\\033[1mDataset size:\\033[0m {len(df)} rows, {len(df.columns)} columns')\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    "if protected_attribute in df.columns and outcome_column in df.columns:\n",
                    "    rates = df.groupby(protected_attribute)[outcome_column].mean().sort_values(ascending=False)\n",
                    "    print('\\n=== Group Selection Rates ===')\n",
                    "    display(rates.to_frame('Selection Rate').style.background_gradient(cmap='Blues'))\n",
                    "    dir_value = rates.min() / rates.max() if rates.max() else 1.0\n",
                    "    spd_value = rates.max() - rates.min()\n",
                    "    print('\\n=== Fairness Metrics ===')\n",
                    "    print(f'\\033[1mDIR (Disparate Impact Ratio):\\033[0m {dir_value:.4f} (Ideal: >= 0.8)')\n",
                    "    print(f'\\033[1mSPD (Statistical Parity Difference):\\033[0m {spd_value:.4f} (Ideal: close to 0)')\n",
                    "    plt.figure(figsize=(8, 5))\n",
                    "    ax = sns.barplot(x=rates.index, y=rates.values, palette='viridis')\n",
                    "    ax.set_title('Favorable Outcome Selection Rate by Group', fontsize=14, fontweight='bold')\n",
                    "    ax.set_ylabel('Selection Rate')\n",
                    "    ax.set_xlabel(protected_attribute)\n",
                    "    plt.show()\n",
                    "else:\n",
                    "    print('⚠️ Please set protected_attribute and outcome_column above to calculate metrics.')\n",
                ],
            ),
            _notebook_cell(
                "markdown",
                [
                    "## 🤖 Gemini AI Prompt Starter\n",
                    "\n",
                    "Run this cell to generate a prompt that you can paste into Gemini or ChatGPT for a narrative fairness audit.\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    "prompt = f\"\"\"\n",
                    "You are an expert ML fairness auditor.\n",
                    "Please analyze the following dataset metrics and explain the potential fairness risks in plain English:\n",
                    "- Protected Attribute: {protected_attribute}\n",
                    "- Outcome Column: {outcome_column}\n",
                    "- Disparate Impact Ratio (DIR): {dir_value:.4f}\n",
                    "- Statistical Parity Difference (SPD): {spd_value:.4f}\n",
                    "What are the immediate implications of these metrics, and what remediation steps would you recommend?\n",
                    "\"\"\"\n",
                    "print(prompt)\n",
                ],
            ),
        ],
    }

    buffer = BytesIO(json.dumps(notebook, indent=2).encode("utf-8"))
    buffer.seek(0)
    return buffer


def build_what_if_export(df: pd.DataFrame, metadata: dict[str, Any]) -> BytesIO:
    buffer = BytesIO()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        archive.writestr("standardized_dataset.csv", df.to_csv(index=False))
        archive.writestr("metadata.json", json.dumps(metadata, indent=2, default=str))
        
        launch_script = (
            "import pandas as pd\n"
            "from witwidget.notebook.visualization import WitWidget\n"
            "import json\n\n"
            "# Run this in a Jupyter/Colab environment\n"
            "df = pd.read_csv('standardized_dataset.csv')\n"
            "with open('metadata.json', 'r') as f:\n"
            "    meta = json.load(f)\n\n"
            "print('Starting What-If Tool with dataset...')\n"
            "wit = WitWidget(df.values.tolist(), df.columns.tolist())\n"
            "wit\n"
        )
        archive.writestr("launch_wit.py", launch_script)

        readme_content = (
            "# 🔬 bAIsed What-If Tool (WIT) Export\n\n"
            "This bundle provides everything needed to instantly launch Google's What-If Tool using your standardized dataset.\n\n"
            "## 📦 What's Inside\n\n"
            "| File | Description |\n"
            "|---|---|\n"
            "| `standardized_dataset.csv` | Your cleaned, standardized dataset ready for WIT. |\n"
            "| `metadata.json` | Protected attributes, outcome columns, and analysis context. |\n"
            "| `launch_wit.py` | A starter script to launch WIT in Jupyter or Colab. |\n\n"
            "## 🚀 Quick Start Guide\n\n"
            "The easiest way to use this is in a Jupyter Notebook or Google Colab environment.\n\n"
            "1. **Upload** this folder to your Colab workspace or local Jupyter environment.\n"
            "2. **Install WIT** if you haven't already:\n"
            "   ```bash\n"
            "   pip install witwidget\n"
            "   ```\n"
            "3. **Run the script** (or copy its contents into a notebook cell):\n"
            "   ```python\n"
            "   import launch_wit\n"
            "   ```\n\n"
            "### 🕵️‍♀️ What to look for in WIT:\n"
            "- Compare performance slices using the protected attribute.\n"
            "- Experiment with counterfactuals to see what changes would flip an outcome.\n"
            "- Visualize threshold boundaries for subgroups.\n"
        )
        archive.writestr("README.md", readme_content)

    buffer.seek(0)
    return buffer
