from __future__ import annotations

import base64
import json
from io import BytesIO
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

import pandas as pd


def _notebook_cell(cell_type: str, source: list[str]) -> dict[str, Any]:
    cell: dict[str, Any] = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source,
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell


def build_colab_notebook(
    df: pd.DataFrame,
    metadata: dict[str, Any],
) -> BytesIO:
    csv_payload = df.to_csv(index=False).encode("utf-8")
    encoded_csv = base64.b64encode(csv_payload).decode("ascii")
    metadata_json = json.dumps(metadata, indent=2)

    protected = metadata.get("protected_attribute") or ""
    outcome = metadata.get("outcome_column") or ""

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "colab": {"name": "bAIsed fairness audit export.ipynb"},
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
        },
        "cells": [
            _notebook_cell(
                "markdown",
                [
                    "# bAIsed Fairness Audit Export\n",
                    "\n",
                    "This notebook was generated by bAIsed for Google Colab exploration.\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    "import base64\n",
                    "import io\n",
                    "import json\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    f"metadata = json.loads({metadata_json!r})\n",
                    f"csv_bytes = base64.b64decode({encoded_csv!r})\n",
                    "df = pd.read_csv(io.BytesIO(csv_bytes))\n",
                    "df.head()\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    f"protected_attribute = {protected!r} or metadata.get('protected_attribute')\n",
                    f"outcome_column = {outcome!r} or metadata.get('outcome_column')\n",
                    "print('Protected attribute:', protected_attribute)\n",
                    "print('Outcome column:', outcome_column)\n",
                    "print('Rows:', len(df))\n",
                    "print('Columns:', list(df.columns))\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    "if protected_attribute in df.columns and outcome_column in df.columns:\n",
                    "    rates = df.groupby(protected_attribute)[outcome_column].mean().sort_values(ascending=False)\n",
                    "    display(rates.to_frame('selection_rate'))\n",
                    "    dir_value = rates.min() / rates.max() if rates.max() else 1.0\n",
                    "    spd_value = rates.max() - rates.min()\n",
                    "    print(f'DIR: {dir_value:.4f}')\n",
                    "    print(f'SPD: {spd_value:.4f}')\n",
                    "    ax = rates.plot(kind='bar', title='Selection rate by group')\n",
                    "    ax.set_ylabel('Selection rate')\n",
                    "    plt.show()\n",
                    "else:\n",
                    "    print('Choose protected_attribute and outcome_column above, then rerun this cell.')\n",
                ],
            ),
            _notebook_cell(
                "markdown",
                [
                    "## Gemini Prompt Starter\n",
                    "\n",
                    "Use this section to paste bAIsed metrics into Gemini for a narrative fairness audit.\n",
                ],
            ),
            _notebook_cell(
                "code",
                [
                    "prompt = f\"\"\"\n",
                    "You are a fairness auditor. Explain this dataset audit in plain English.\n",
                    "Protected attribute: {protected_attribute}\n",
                    "Outcome column: {outcome_column}\n",
                    "Rows: {len(df)}\n",
                    "Columns: {list(df.columns)}\n",
                    "\"\"\"\n",
                    "print(prompt)\n",
                ],
            ),
        ],
    }

    buffer = BytesIO(json.dumps(notebook, indent=2).encode("utf-8"))
    buffer.seek(0)
    return buffer


def build_what_if_export(df: pd.DataFrame, metadata: dict[str, Any]) -> BytesIO:
    buffer = BytesIO()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        archive.writestr("standardized_dataset.csv", df.to_csv(index=False))
        archive.writestr("metadata.json", json.dumps(metadata, indent=2, default=str))
        archive.writestr(
            "README.md",
            "\n".join(
                [
                    "# bAIsed What-If Tool Export",
                    "",
                    "This bundle contains the standardized dataset produced by bAIsed.",
                    "",
                    "Files:",
                    "- `standardized_dataset.csv`: cleaned dataset used by the fairness audit",
                    "- `metadata.json`: selected protected/outcome columns and dataset context",
                    "",
                    "Suggested workflow:",
                    "1. Open Google Colab or a TensorBoard What-If Tool environment.",
                    "2. Upload `standardized_dataset.csv`.",
                    "3. Use the metadata fields to choose the protected and outcome columns.",
                    "4. Compare slices, counterfactuals, and group-level outcomes.",
                    "",
                    "Note: Google's What-If Tool inspects model behavior. This export prepares the dataset and audit context for that workflow.",
                ]
            ),
        )
    buffer.seek(0)
    return buffer
